version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    assignees:
      - 'derogab'
    labels:
      - 'dependencies'
    groups:
      github-actions-major:
        update-types:
          - 'major'
      github-actions-minor:
        update-types:
          - 'minor'
      github-actions-patch:
        update-types:
          - 'patch'

  # Maintain dependencies for Python
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'monthly'
    assignees:
      - 'derogab'
    labels:
      - 'dependencies'
    groups:
      pip-minor:
        update-types:
          - 'minor'
      pip-patch:
        update-types:
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
