version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    assignees:
      - 'derogab'
    labels:
      - 'dependencies'

  # Maintain dependencies for Python
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'monthly'
    assignees:
      - 'derogab'
    labels:
      - 'dependencies'
